### PR TITLE
Her 17 migration for renaming kit requests to orders

### PR DESCRIPTION
**Pull request by olesiamironenko**
## Issue

https://raquelanaroman.atlassian.net/browse/<JIRA_TICKET_ID>

Create a migration that renames the kit_requests table to orders

## Changes

1. I generated the migratiion for renaming the table kit_requests to orders.
2. I edited the code in the migration file by adding "rename_table :kit_requests, :orders" to the "change" method.
3. I run the migration.
4. I staged, committed, and pushed changes to the github repository.

### Review Checklist

- [ ] I have documented my code with code comments.

### CODE REVIEW

**Comment by raquii** [comment]
Similar to my comments to @mhope21 in #9, you would normally need to fix the [failing tests](https://github.com/Code-the-Dream-School/herring-team-3/actions/runs/11979047555/job/33400367023?pr=12) before this PR can be approved.

Since this is a subtask ticket and we are renaming the entire model, I am going to ask you to complete the other subtask, https://raquelanaroman.atlassian.net/browse/HER-18, and complete it on this same branch. 

Otherwise, we will break tests for everyone if we merge this "as is", (which is why merging isn't allowed when tests fail).

The migration looks great, though! ✅

**Review by mhope21 — APPROVED** [review]
Looks great. Very thorough. We are encouraged to comment our changes I think, but this is really good. I think there are some conflicts to resolve on your PR. Check it out.

**Comment by olesiamironenko** [comment]
> Looks great. Very thorough. We are encouraged to comment our changes I think, but this is really good. I think there are some conflicts to resolve on your PR. Check it out.

Thanks, Marcia!

**Review by dewi-anggraini — DISMISSED** [review]
This looks great.

**Review by raquii — CHANGES_REQUESTED** [review]
Good. Just one thing: I think we missed replacing `kit_requests` here:

https://github.com/Code-the-Dream-School/herring-team-3/blob/aefbaaa147543e3ff2b95b5d84a328da8b1125ed/app/models/user.rb#L10

**Comment by olesiamironenko** [comment]
> Good. Just one thing: I think we missed replacing `kit_requests` here:
> 
> https://github.com/Code-the-Dream-School/herring-team-3/blob/aefbaaa147543e3ff2b95b5d84a328da8b1125ed/app/models/user.rb#L10

Since there are those lines in order model:
  belongs_to :kit
  belongs_to :user
  
 and in user model:
   has_many :orders
   
 should it be this line in kit model?
   has_many :orders

**Review by raquii — APPROVED** [review]

**Review by mhope21 — APPROVED** [review]
Looks good.

**Pull request merged**
