### PR TITLE
HER-6 FE replace name with firstname lastname

### PR DESCRIPTION
**Pull request by mhope21**
HER-6: FE: Replace name inputs with firstName, lastName inputs in user forms
## Issue

https://raquelanaroman.atlassian.net/browse/HER-6

As a user, I would like to be able to input my first and last name into a form when being asked for my information.

replace any name input fields used to create or update Users with a firstName and lastName field 

- HER-5: https://github.com/Code-the-Dream-School/herring-team-3/pull/9

## Changes

For Registration, Donation, RequestKit, EditModal, and NewUser:
* remove name field, add first name and last name field
* remove useState for name, add for first name and last name
* remove name for data sent to backend, add first name and last name
* remove name for clearing field, add first name and last name
 
### Review Checklist

- [x] I have documented my code with code comments.

### CODE REVIEW

**Comment by mhope21** [comment]
I have looked at the details of the failing check. I think I see the problem being a duplicate require. Should I be the one figuring out how to fix this? Also, it says my branch is now out of date with main. If I pull from main again, could this be fixed?

**Review by trca831 — APPROVED** [review]
Looks good to me!

**Review by dewi-anggraini — APPROVED** [review]
LGTM

**Review by raquii — APPROVED** [review]

**Comment by trca831** [comment]
LGTM!

**Pull request merged**
