### PR TITLE
HER-5: migration add firstname lastname to user

### PR DESCRIPTION
**Pull request by mhope21**
HER-5: Migration: Add first name and last name to User Model

## Issue

https://raquelanaroman.atlassian.net/browse/HER-5

As a user, I would like my first and last name to be clearly defined as separate.

Acceptance Criteria
Add two string attributes to the User model:

first_name, null: false

last_name

## Changes

Added 2 columns to the users table, first_name and last_name. Modified the schema to include null: false on first_name.

### Review Checklist

- [x ] I have documented my code with code comments.

### CODE REVIEW

**Review by raquii — APPROVED** [review]

**Comment by raquii** [comment]
@mhope21 Take a look at the failing tests in the checks section of this PR: you may have to update some test fixtures as part of your changes.

Make sure to `git pull` on your local, as I merged the recent updates from `main` into the remote of this branch

**Comment by mhope21** [comment]
Do you want me to fix the tests before merging?

**Comment by mhope21** [comment]
Also, I did git pull when I started working this morning. Are you letting me know to do it again because you have made changes since then, or does it look like I forgot to do it? Just clarifying, trying to make sure I didn't make a mistake.

**Comment by raquii** [comment]
I used the GitHub Pull Request UI to [merge `main` into this branch](https://github.com/Code-the-Dream-School/herring-team-3/pull/9/commits/f2b0af085f22ef5a6069fdf095197f4cb56914f4), `HER-5-Migration-Add-firstname-lastname-to-User`, to make it use the updates I made to the` .github` directory files, which included getting your test suite to run automatically on the pull request.

You will not be able to merge this PR into `main` without fixing the failing tests, **however**, before you go to fix the tests in your local  `HER-5-Migration-Add-firstname-lastname-to-User` branch, you need to run `git pull` to make _local_ match the _remote_ otherwise, when you go to `push` changes, you are going to get an error.

**Review by raquii — APPROVED** [review]

**Review by trca831 — APPROVED** [review]
Looks good to me!

**Comment by dewi-anggraini** [comment]
Looks good to me.

**Review by dewi-anggraini — APPROVED** [review]

**Comment by mhope21** [comment]
Thanks. About to merge.

**Pull request merged**
